### ISSUE TITLE
Queries has not been accessed since - Presto

### ISSUE THREAD

**Issue by SwapnaRavi21** [prestodb/benchto#64]
Hi 
I am running queries on Presto cluster and I get the following error , after 10 mins. Any idea? Is there any time limit in presto where the query gets killed by itself like this & hence we face the below issue?

I have similar issue com.facebook.presto.spi.PrestoException: Query 20191111_162609_00141_vrkhx has not been accessed since 2019-11-11T16:32:05.517Z: currentTime 2019-11-11T16:37:06.260Z

**Comment by rongrong** [comment]
Presto server relies on Presto client constantly pooling the query results to know that the client is still interested in the query results. If the client stops pooling, after certain time Presto will assume the client is no longer interested in the query result and abandon the query to save unnecessary compute. This unfortunately means that if your connection between client and server is unstable and client became offline for some time for whatever reason, server would also abandon the query assuming the client is no longer interested.

**Comment by SwapnaRavi21** [comment]
So Can I change this time ? Can I set this property in the presto-config?

**Comment by rongrong** [comment]
You can change the value of `query.client.timeout` in `config.properties`.

**Comment by arghya18** [comment]
I tried the suggested setting on coordinator config.properties but still got the same issue.
query.client.timeout=4h

**Comment by forrestlmj** [comment]
@arghya18  have you solved the problem?

**Comment by BilalKHA95** [comment]
it's possible to override this parameter in the SQL request directly ? to parametrize the execution time just for a specific query ?
